name = "portfolio-contact"
main = "functions/contact.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
name = "portfolio-contact"
route = "/*"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[triggers]
routes = ["/api/contact"]

[compatibility_flags]
nodejs_compat = true

[env.production.vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "/api/contact"
zone_id = "*" 